# Generated by Django 3.0 on 2020-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
