# Generated by Django 3.0 on 2020-04-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200401_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='file_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
