# Generated by Django 3.0 on 2020-04-01 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200401_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
