# Generated by Django 3.0.4 on 2020-04-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20200401_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='inventory',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
