# Generated by Django 3.0.4 on 2020-04-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200401_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
