# Generated by Django 3.0.4 on 2020-04-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        ('listing', '0009_auto_20200401_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('file_path', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
    ]
