# Generated by Django 3.0.4 on 2020-04-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200415_1503'),
        ('listing', '0011_auto_20200404_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedlisting',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction'),
        ),
    ]
