# Generated by Django 3.0.4 on 2020-04-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20200415_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedlisting',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.Listing'),
        ),
    ]
