# Generated by Django 3.0 on 2020-04-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
